apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "flood.fullname" . }}
  labels:
    {{- include "flood.labels" . | nindent 4 }}
data:
  port: {{ .Values.flood.port | quote }}
  baseURI: {{ .Values.flood.baseURI | quote }}
  {{- if .Values.flood.allowedPaths }}
  allowedPaths: {{ join "," .Values.flood.allowedPaths | quote }}
  {{- end }}
